# Generated by Django 3.2.11 on 2022-02-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image_url',
            field=models.CharField(max_length=500, null=True, verbose_name='imageUrl'),
        ),
    ]
