# Generated by Django 3.2.11 on 2022-02-06 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='imageUrl'),
        ),
    ]
